from .admin_command import call_admin_panel
from .admin_command import users_info
from .admin_command import set_add_menu
from .admin_command import set_remove_menu
from .admin_command import show_applications
from .admin_command import auto_add_by_application
from .admin_command import manual_add_user
from .admin_command import delete_user_by_initials
from .admin_command import delete_all_from_group
