version: "3.7"

services:
    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile

        container_name: app-react

        tty: true

        depends_on:
            - backend

        environment:
            BACKEND_HOST: localhost

        networks:
            - app

        ports:
            - 3000:3000

        restart: unless-stopped

        volumes:
            - ./frontend:/app/frontend

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        
        container_name: app-laravel

        depends_on:
            - psql

        env_file:
            - .env-laravel

        networks:
            - app

        ports:
            - 8000:8000

        restart: unless-stopped

        volumes:
            - ./backend:/app/backend


    psql:
        image: postgres:14

        container_name: app-psql

        env_file:
            - .env
        
        ports:
          - 5432:5432

        restart: always

        volumes:
            - databaseData:/var/lib/postgresql/data


networks:
    app:
        driver: bridge

volumes:
    databaseData:
        driver: local